### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by sc23333** [zcccccz/CausalWalk#2]
Hello, does this project have a requirements.txt file? If so, could you please provide it? Thank you!

**Comment by zcccccz** [comment]
requirements.txt has been released.

**Comment by bomb622** [comment]
requirements.txt 文件中有一些类似@ file:///tmp/build/80754af9/cryptography_1616769286105/work的文件，如何获取这些包？

**Comment by rrrrrby111** [comment]
Dear Authors,
There are some entries like @ file:///tmp/build/80754af9/cryptography_1616769286105/work in the requirements.txt file. Could you please tell me how to obtain the versions of these packages?
